// Using Web Crypto API for Edge Runtime compatibility

const PASSWORD_REGEX = /^[0-9a-fA-F]{6,}$/;

export function validateCredentials(
  username: string,
  password: string
): boolean {
  const validUser = process.env.MOCK_USERNAME ?? "admin";
  const validPass = process.env.MOCK_PASSWORD_HEX ?? "";

  if (!PASSWORD_REGEX.test(password)) return false;
  if (username !== validUser) return false;
  if (password !== validPass) return false;
  return true;
}

export function generateToken(): string {
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return Array.from(array)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export function isValidHexPassword(password: string): boolean {
  return PASSWORD_REGEX.test(password);
}

export const COOKIE_NAME = "auth_token";

export function getCookieMaxAge(): number {
  return parseInt(process.env.COOKIE_MAX_AGE ?? "604800", 10);
}

export function buildSetCookieHeader(token: string): string {
  const maxAge = getCookieMaxAge();
  const isProduction = process.env.NODE_ENV === "production";
  const secure = isProduction ? "; Secure" : "";
  return `${COOKIE_NAME}=${token}; HttpOnly${secure}; SameSite=Strict; Max-Age=${maxAge}; Path=/`;
}

export function buildClearCookieHeader(): string {
  return `${COOKIE_NAME}=; HttpOnly; SameSite=Strict; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/`;
}

export function extractTokenFromCookies(
  cookieHeader: string | null
): string | null {
  if (!cookieHeader) return null;
  const match = cookieHeader.match(new RegExp(`${COOKIE_NAME}=([^;]+)`));
  return match?.[1] ?? null;
}

export function isValidToken(token: string | null): boolean {
  if (!token) return false;
  // Token is a 64-char hex string generated by generateToken()
  return /^[0-9a-f]{64}$/.test(token);
}
